#!/bin/bash
# HIS Platform Test Runner
# Runs both unit tests and E2E tests, generates reports

set -e

PROJECT_ROOT=$(cd "$(dirname "$0")/.." && pwd)
REPORT_DIR="$PROJECT_ROOT/report"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

echo "========================================"
echo "HIS Platform Test Suite"
echo "========================================"
echo "Project Root: $PROJECT_ROOT"
echo "Report Directory: $REPORT_DIR"
echo "Timestamp: $TIMESTAMP"
echo ""

# Create report directory
mkdir -p "$REPORT_DIR"
mkdir -p "$REPORT_DIR/unit"
mkdir -p "$REPORT_DIR/e2e"
mkdir -p "$REPORT_DIR/coverage"

# Function to generate summary report
generate_summary() {
    local unit_passed=$1
    local unit_failed=$2
    local e2e_passed=$3
    local e2e_failed=$4
    local coverage_pct=$5

    SUMMARY_FILE="$REPORT_DIR/test_summary_$TIMESTAMP.md"

    cat > "$SUMMARY_FILE" << EOF
# HIS Platform Test Report

**Generated:** $(date)

## Test Summary

| Test Type | Passed | Failed | Total | Pass Rate |
|-----------|--------|--------|-------|-----------|
| Unit Tests | $unit_passed | $unit_failed | $((unit_passed + unit_failed)) | $(echo "scale=2; $unit_passed * 100 / ($unit_passed + $unit_failed)" | bc 2>/dev/null || echo "N/A")% |
| E2E Tests | $e2e_passed | $e2e_failed | $((e2e_passed + $e2e_failed)) | $(echo "scale=2; $e2e_passed * 100 / ($e2e_passed + $e2e_failed)" | bc 2>/dev/null || echo "N/A")% |

## Code Coverage

- Line Coverage: ${coverage_pct}%
- Branch Coverage: ${coverage_pct}%
- Target: 90%+

## Reports

- Unit Test Report: \`report/unit/unit_report_$TIMESTAMP.html\`
- Coverage Report: \`report/coverage/index.html\`
- E2E Test Report: \`report/e2e/e2e_report_$TIMESTAMP.html\`

## Quality Gates

- [ ] Unit Test Pass Rate >= 90%
- [ ] E2E Test Pass Rate >= 90%
- [ ] Line Coverage >= 90%
- [ ] Branch Coverage >= 90%

---
*Generated by HIS Platform Test Runner*
EOF

    echo "Summary report: $SUMMARY_FILE"
}

# Run Unit Tests with Coverage
echo "========================================"
echo "1. Running Unit Tests with Coverage"
echo "========================================"

cd "$PROJECT_ROOT"

# Run Maven test with JaCoCo coverage
mvn clean test jacoco:report -Dmaven.test.failure.ignore=true

# Check if tests completed
if [ -f "$PROJECT_ROOT/target/site/jacoco/index.html" ]; then
    echo "Coverage report generated"
    cp -r "$PROJECT_ROOT/target/site/jacoco/"* "$REPORT_DIR/coverage/"

    # Extract coverage percentage
    COVERAGE_PCT=$(grep -oP '(?<=<td class="ctr2">)[0-9]+(?=%)' "$PROJECT_ROOT/target/site/jacoco/index.html" 2>/dev/null | head -1 || echo "0")

    # Count test results
    UNIT_PASSED=$(grep -c "tests=\"[0-9]*\"" "$PROJECT_ROOT"/his-modules/*/target/surefire-reports/*.xml 2>/dev/null | wc -l || echo "0")
    UNIT_FAILED=$(find "$PROJECT_ROOT"/his-modules/*/target/surefire-reports -name "TEST-*.xml" -exec grep -l 'errors="[1-9]' {} \; 2>/dev/null | wc -l || echo "0")
else
    COVERAGE_PCT="0"
    UNIT_PASSED="0"
    UNIT_FAILED="0"
fi

echo "Unit Tests: Passed=$UNIT_PASSED, Failed=$UNIT_FAILED"
echo "Coverage: $COVERAGE_PCT%"
echo ""

# Run E2E Tests
echo "========================================"
echo "2. Running E2E Tests"
echo "========================================"

cd "$PROJECT_ROOT/scripts"

# Check if Python and dependencies are available
if command -v python3 &> /dev/null; then
    pip3 install -r requirements.txt -q 2>/dev/null || true

    # Run E2E tests
    python3 e2e_test.py 2>&1 | tee "$REPORT_DIR/e2e/e2e_output_$TIMESTAMP.log"

    # Parse E2E results
    if [ -f "$REPORT_DIR/e2e_report_$TIMESTAMP.json" ]; then
        E2E_PASSED=$(grep -o '"passed": [0-9]*' "$REPORT_DIR/e2e_report_$TIMESTAMP.json" | grep -o '[0-9]*' || echo "0")
        E2E_FAILED=$(grep -o '"failed": [0-9]*' "$REPORT_DIR/e2e_report_$TIMESTAMP.json" | grep -o '[0-9]*' || echo "0")
    else
        E2E_PASSED="0"
        E2E_FAILED="0"
    fi
else
    echo "Python3 not found, skipping E2E tests"
    E2E_PASSED="0"
    E2E_FAILED="0"
fi

echo ""
echo "E2E Tests: Passed=$E2E_PASSED, Failed=$E2E_FAILED"
echo ""

# Generate Summary Report
echo "========================================"
echo "3. Generating Summary Report"
echo "========================================"

generate_summary "$UNIT_PASSED" "$UNIT_FAILED" "$E2E_PASSED" "$E2E_FAILED" "$COVERAGE_PCT"

echo ""
echo "========================================"
echo "Test Run Complete"
echo "========================================"
echo "Reports available in: $REPORT_DIR"
echo ""

# Quality Gate Check
if [ "$COVERAGE_PCT" -lt 90 ]; then
    echo "⚠️  Warning: Code coverage ($COVERAGE_PCT%) is below 90% target"
fi

if [ "$UNIT_FAILED" -gt 0 ] || [ "$E2E_FAILED" -gt 0 ]; then
    echo "⚠️  Warning: Some tests failed"
    exit 1
fi

echo "✅ All quality gates passed!"
exit 0