server:
  port: 8085

spring:
  application:
    name: his-module-lis
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:data/his_lis.db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=10m

logging:
  level:
    root: INFO
    com.yhj.his: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html